/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thesisdatabase;

import java.util.ArrayList;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author waltersquires
 */
public class AddAppPanel extends javax.swing.JPanel {

    /**
     * Creates new form addApp
     */
    public AddAppPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JSON = new javax.swing.JTextArea();
        addApp = new javax.swing.JButton();
        appName = new javax.swing.JTextField();
        appNameLabel = new javax.swing.JLabel();
        JSONLabel = new javax.swing.JLabel();
        developerLabel = new javax.swing.JLabel();
        developerName = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));

        JSON.setColumns(20);
        JSON.setRows(5);
        jScrollPane1.setViewportView(JSON);

        addApp.setText("Submit");
        addApp.setPreferredSize(new java.awt.Dimension(100, 30));
        addApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAppActionPerformed(evt);
            }
        });

        appName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appNameActionPerformed(evt);
            }
        });

        appNameLabel.setText("App Name:");

        JSONLabel.setText("JSON:");

        developerLabel.setText("Developer:");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(appNameLabel)
                .addGap(6, 6, 6)
                .addComponent(appName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(developerLabel)
                .addGap(6, 6, 6)
                .addComponent(developerName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(JSONLabel))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(addApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(cancelButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(appNameLabel))
                    .addComponent(appName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(developerLabel))
                    .addComponent(developerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(JSONLabel)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void appNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appNameActionPerformed

    private void addAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAppActionPerformed
    try {
        Application newApp = ThesisDatabase.readJSON(JSON.getText());
        ArrayList<String> data = newApp.appData();
        data.add(ThesisDatabase.userName);
        data.add(appName.getText());
        data.add(developerName.getText());
        int appId = ThesisDatabase.addNewApp(data);
        
        ArrayList<?> permissions = newApp.getInfo();
        if(newApp instanceof AndroidApplication)
        {
            for(int i = 0; i< permissions.size(); i++)
            {
                ThesisDatabase.addpermission(appId, (Permission)permissions.get(i));
            }
            
        }
        else if (newApp instanceof IOSApplication)
        {
            for(int i = 0; i< permissions.size(); i++)
            {
                ThesisDatabase.addPackage(appId, (String)permissions.get(i));

            }

            
        }
               
       
      Object[] options1 = {"No, I'd like to go back",
                          "Yes, I'd like to continue"};
      int n = JOptionPane.showOptionDialog(ThesisDatabase.popUp,
      "The data you submitted has been added to the database. "
      + "\nWould you like to continue?",
      "Success",
      JOptionPane.YES_NO_OPTION,
      JOptionPane.QUESTION_MESSAGE,
      null,     
      options1,  
      options1[0]);
      if (n==0)
      {
            ThesisDatabase.window.selectPanel(2);
      }
      
              clearFields();

        }
     catch (SQLException ex)
    {
        Logger.getLogger(AddAppPanel.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    catch (org.json.JSONException e)
    {
      JOptionPane.showMessageDialog(ThesisDatabase.popUp,
          "Something appears to be wrong with the JSON file you have submitted. Please try again",
          "Whoops!",
          JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_addAppActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        clearFields();
        ThesisDatabase.window.selectPanel(2);        
    }//GEN-LAST:event_cancelButtonActionPerformed
private void clearFields()
{
    appName.setText("");
    developerName.setText("");
    JSON.setText("");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JSON;
    private javax.swing.JLabel JSONLabel;
    private javax.swing.JButton addApp;
    private javax.swing.JTextField appName;
    private javax.swing.JLabel appNameLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel developerLabel;
    private javax.swing.JTextField developerName;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
