/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thesisdatabase;

import java.util.ArrayList;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author waltersquires
 */
public class AddAppPanel extends javax.swing.JPanel {

    /**
     * Creates new form addApp
     */
    public AddAppPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JSON = new javax.swing.JTextArea();
        addApp = new javax.swing.JButton();
        appName = new javax.swing.JTextField();
        appNameLabel = new javax.swing.JLabel();
        developerLabel = new javax.swing.JLabel();
        developerName = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        GenreLabel = new javax.swing.JLabel();
        genreName = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JSON.setColumns(20);
        JSON.setRows(5);
        jScrollPane1.setViewportView(JSON);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 109, 342, 132));

        addApp.setText("Submit");
        addApp.setPreferredSize(new java.awt.Dimension(100, 30));
        addApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAppActionPerformed(evt);
            }
        });
        add(addApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 270, 92, -1));

        appName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appNameActionPerformed(evt);
            }
        });
        add(appName, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 11, 164, -1));

        appNameLabel.setText("App Name:");
        add(appNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 17, -1, -1));

        developerLabel.setText("Developer:");
        add(developerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        developerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                developerNameActionPerformed(evt);
            }
        });
        add(developerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 164, -1));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 270, -1, -1));

        jLabel1.setText("JSON:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 88, 39, -1));
        add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        GenreLabel.setText("Genre:");
        add(GenreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        add(genreName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAppActionPerformed
    try {
        Application newApp = ThesisDatabase.readJSON(JSON.getText());
        ArrayList<String> data = newApp.appData();
        data.add(ThesisDatabase.userName);
        data.add(appName.getText());
        data.add(developerName.getText());
        data.add(genreName.getText());

        
        boolean exists = ThesisDatabase.isRepeat(data.get(0),data.get(4));
         if (exists)
        {
            Object[] options1 = {"No",
                                "Yes"};
             int n = JOptionPane.showOptionDialog(ThesisDatabase.popUp,
             "App you would like to submit may already exist in the database"
            + "\nWould you like to add it anyway?",
      "Success",
      JOptionPane.YES_NO_OPTION,
      JOptionPane.QUESTION_MESSAGE,
      null,     
      options1,  
      options1[0]);
      if (n==1)
      {
            finishAdding(newApp, data);
      }
        }
        else
            finishAdding(newApp,data);
    }
     catch (SQLException ex)
    {
        Logger.getLogger(AddAppPanel.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    catch (org.json.JSONException e)
    {
      JOptionPane.showMessageDialog(ThesisDatabase.popUp,
          "Something appears to be wrong with the JSON file you have submitted. Please try again",
          "Whoops!",
          JOptionPane.ERROR_MESSAGE);
    }
    }
    

    private void finishAdding(Application newApp, ArrayList<String> data)
    {
        try
        {
        int appId = ThesisDatabase.addNewApp(data);
        ArrayList<?> permissions = newApp.getInfo();
        if(newApp instanceof AndroidApplication)
        {
            for(int i = 0; i< permissions.size(); i++)
            {
                ThesisDatabase.addpermission(appId, (Permission)permissions.get(i));
            }
            
        }
        else if (newApp instanceof IOSApplication)
        {
            for(int i = 0; i< permissions.size(); i++)
            {
                ThesisDatabase.addPackage(appId, (String)permissions.get(i));

            }

            
        }
               
       
      Object[] options1 = {"No, I'd like to go back",
                          "Yes, I'd like to continue"};
      int n = JOptionPane.showOptionDialog(ThesisDatabase.popUp,
      "The data you submitted has been added to the database. "
      + "\nWould you like to continue?",
      "Success",
      JOptionPane.YES_NO_OPTION,
      JOptionPane.QUESTION_MESSAGE,
      null,     
      options1,  
      options1[0]);
      if (n==0)
      {
            ThesisDatabase.window.selectPanel(2);
      }
              clearFields();
     }
     catch (SQLException ex)
    {
        Logger.getLogger(AddAppPanel.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_addAppActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        clearFields();
        ThesisDatabase.window.selectPanel(2);        
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void appNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appNameActionPerformed

    private void developerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_developerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_developerNameActionPerformed
private void clearFields()
{
    appName.setText("");
    developerName.setText("");
    genreName.setText("");
    JSON.setText("");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GenreLabel;
    private javax.swing.JTextArea JSON;
    private javax.swing.JButton addApp;
    private javax.swing.JTextField appName;
    private javax.swing.JLabel appNameLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel developerLabel;
    private javax.swing.JTextField developerName;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JTextField genreName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
