/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thesisdatabase;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sean
 */
public class AppPrivilegesPanel extends javax.swing.JPanel {

    /**
     * Creates new form AppPrivilegesPanel
     */
    public AppPrivilegesPanel() {
        initComponents();
        
        tables = new ArrayList<JTable>();
        tables.add(overPrivilegedTable);
        tables.add(underPrivilegedTable);
        tables.add(underAndOverTable);
        tables.add(correctlyPrivilegedTable);
    }
    

    public void initialize() {
        populateTables();
        calculateStats();
    }
    
    private void populateTables() {
        try {
           ArrayList<ResultSet> app = ThesisDatabase.getAppsbyStatus();
           for(int i = 0; i<4; i++) {
               while (app.get(i).next()) {
                   tables.get(i).setModel(DbUtils.resultSetToTableModel(app.get(i)));
               }
           }
           
           ThesisDatabase.window.selectPanel(3);
        } catch (SQLException ex) {
            Logger.getLogger(QueriesPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void calculateStats() {
        List<Integer> stats = ThesisDatabase.getStaticAnalysisStats();
        int goodAndroidApps  = stats.get(0);
        int underAndroidApps = stats.get(1) + stats.get(3);
        int overAndroidApps  = stats.get(2) + stats.get(3);
        int totalAndroidApps = goodAndroidApps + stats.get(1) + stats.get(2) + stats.get(3);
        
        properAndroidNumber.setText(goodAndroidApps + "\t\t\t" + (100.0*goodAndroidApps/totalAndroidApps)  + "%");
        underAndroidNumber.setText(underAndroidApps + "\t\t\t" + (100.0*underAndroidApps/totalAndroidApps) + "%");
        overAndroidNumber.setText(overAndroidApps   + "\t\t\t" + (100.0*overAndroidApps/totalAndroidApps)  + "%");
        /*
    private javax.swing.JLabel overAndroidNumber;
    private javax.swing.JTable overPrivilegedTable;
    private javax.swing.JLabel overiOSNumber;
    private javax.swing.JLabel properAndroidNumber;
    private javax.swing.JLabel properiOSNumber;
    private javax.swing.JTable underAndOverTable;
    private javax.swing.JLabel underAndroidNumber;
    private javax.swing.JTable underPrivilegedTable;
    private javax.swing.JLabel underiOSNumber;
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        overPrivilegedTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        underPrivilegedTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        underAndOverTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        correctlyPrivilegedTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        overiOSNumber = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        properiOSNumber = new javax.swing.JLabel();
        underiOSNumber = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        overAndroidNumber = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        properAndroidNumber = new javax.swing.JLabel();
        underAndroidNumber = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setMaximumSize(new java.awt.Dimension(350, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 200));

        overPrivilegedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "App Id", "App Name", "Version Code", "Platform"
            }
        ));
        overPrivilegedTable.setBounds(new java.awt.Rectangle(0, 0, 350, 64));
        overPrivilegedTable.setPreferredSize(new java.awt.Dimension(250, 64));
        jScrollPane1.setViewportView(overPrivilegedTable);

        jPanel1.add(jScrollPane1);

        jTabbedPane1.addTab("Over Privileged", jPanel1);

        jScrollPane2.setMaximumSize(new java.awt.Dimension(350, 200));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(400, 200));

        underPrivilegedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "App Id", "App Name", "Version Code", "Platform"
            }
        ));
        underPrivilegedTable.setBounds(new java.awt.Rectangle(0, 0, 350, 64));
        underPrivilegedTable.setPreferredSize(new java.awt.Dimension(250, 64));
        jScrollPane2.setViewportView(underPrivilegedTable);

        jPanel2.add(jScrollPane2);

        jTabbedPane1.addTab("Under Privileged", jPanel2);

        jScrollPane3.setMaximumSize(new java.awt.Dimension(350, 200));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(400, 200));

        underAndOverTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "App Id", "App Name", "Version Code", "Platform"
            }
        ));
        underAndOverTable.setBounds(new java.awt.Rectangle(0, 0, 350, 64));
        underAndOverTable.setPreferredSize(new java.awt.Dimension(250, 64));
        jScrollPane3.setViewportView(underAndOverTable);

        jPanel3.add(jScrollPane3);

        jTabbedPane1.addTab("Both Over and Under Privileged", jPanel3);

        jScrollPane4.setMaximumSize(new java.awt.Dimension(350, 200));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(400, 200));

        correctlyPrivilegedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "App Id", "App Name", "Version Code", "Platform"
            }
        ));
        correctlyPrivilegedTable.setBounds(new java.awt.Rectangle(0, 0, 350, 64));
        correctlyPrivilegedTable.setPreferredSize(new java.awt.Dimension(250, 64));
        jScrollPane4.setViewportView(correctlyPrivilegedTable);

        jPanel4.add(jScrollPane4);

        jTabbedPane1.addTab("Correctly Privileged", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("   Under Privileged iOS Apps:");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, -1));

        overiOSNumber.setText("<>");
        overiOSNumber.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel5.add(overiOSNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 190, 20));

        jLabel4.setText("   Properly Privileged iOS Apps:");
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setText("   Over Privileged iOS Apps:");
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        properiOSNumber.setText("<>");
        properiOSNumber.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel5.add(properiOSNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 190, 20));

        underiOSNumber.setText("<>");
        underiOSNumber.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel5.add(underiOSNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 190, 20));

        jLabel2.setText("   Under Privileged Android Apps:");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 210, -1));

        overAndroidNumber.setText("<>");
        overAndroidNumber.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel5.add(overAndroidNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 190, 20));

        jLabel6.setText("   Properly Privileged Android Apps:");
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 230, -1));

        jLabel7.setText("   Over Privileged Android Apps:");
        jLabel7.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        properAndroidNumber.setText("<>");
        properAndroidNumber.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel5.add(properAndroidNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 190, 20));

        underAndroidNumber.setText("<>");
        underAndroidNumber.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel5.add(underAndroidNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 190, 20));

        jTabbedPane1.addTab("Statistics", jPanel5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 16;
        add(jTabbedPane1, gridBagConstraints);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(backButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
ThesisDatabase.window.selectPanel(2);        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    
    private List<JTable> tables;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTable correctlyPrivilegedTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel overAndroidNumber;
    private javax.swing.JTable overPrivilegedTable;
    private javax.swing.JLabel overiOSNumber;
    private javax.swing.JLabel properAndroidNumber;
    private javax.swing.JLabel properiOSNumber;
    private javax.swing.JTable underAndOverTable;
    private javax.swing.JLabel underAndroidNumber;
    private javax.swing.JTable underPrivilegedTable;
    private javax.swing.JLabel underiOSNumber;
    // End of variables declaration//GEN-END:variables
}
