/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thesisdatabase;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ButtonGroup;

/**
 *
 * @author waltersquires
 */
public class classifyUnknownFrameworksPanel extends javax.swing.JPanel {
String permission ="";
    /**
     * Creates new form classifyUnknownPermissionsPanel
     */
    public classifyUnknownFrameworksPanel() {
        initComponents();
        groupButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        perm = new javax.swing.JTable();
        back = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        secure = new javax.swing.JRadioButton();
        insecure = new javax.swing.JRadioButton();

        perm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Framework"
            }
        ));
        perm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                permMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(perm);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        secure.setText("Secure");
        secure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secureActionPerformed(evt);
            }
        });

        insecure.setText("Insecure");
        insecure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insecureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(secure)
                    .addComponent(insecure))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(secure)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(insecure)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void groupButton( ) {

        ButtonGroup bg1 = new ButtonGroup( );

        bg1.add(secure);
        bg1.add(insecure);

}
    
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
       boolean isSecure =false;
        if (insecure.isSelected())
            isSecure=false;
        else if (secure.isSelected())
            isSecure=true;
        
        try
        {
          ThesisDatabase.updateFramework(isSecure, permission);
         // perm;
          QueriesPanel.populateUnknownTable2();

        }
        catch (SQLException e ) {
        e.printStackTrace();
       }
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void secureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secureActionPerformed
     // insecure.    //Make it disable the other
    }//GEN-LAST:event_secureActionPerformed

    private void insecureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insecureActionPerformed
     // secure.      //Make it disable the other
    }//GEN-LAST:event_insecureActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
                ThesisDatabase.window.selectPanel(2);
    }//GEN-LAST:event_backActionPerformed

    private void permMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_permMouseClicked
try
{
    int row = perm.getSelectedRow();
    int column =perm.getSelectedColumn();
    permission = (String)perm.getValueAt(row, column);
}
catch(Exception e)
{
    
}
// TODO add your handling code here:
    }//GEN-LAST:event_permMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JRadioButton insecure;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable perm;
    private javax.swing.JRadioButton secure;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
