/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thesisdatabase;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author waltersquires
 */
public class LoginPanel extends java.awt.Panel {

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        UserNameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        userNameInput = new javax.swing.JTextField();
        userPasswordInput = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setMinimumSize(new java.awt.Dimension(400, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserNameLabel.setText("User Name");
        add(UserNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        PasswordLabel.setText("Password");
        add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        add(userNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 180, -1));
        add(userPasswordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 180, -1));

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try 
        {
            boolean login = ThesisDatabase.login((userNameInput.getText()),userPasswordInput.getText());
            if(login)
                System.out.println("Logged in");
            else
                System.out.println("Bad Login");

        }
        catch (SQLException ex) 
        {
                Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField userNameInput;
    private javax.swing.JTextField userPasswordInput;
    // End of variables declaration//GEN-END:variables
}
