/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thesisdatabase;

/**
 *
 * @author waltersquires
 */
public class queriesPanel extends javax.swing.JPanel {

    /**
     * Creates new form queriesPanel
     */
    public queriesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        addAppButton = new javax.swing.JButton();

        welcomeLabel.setText("Welcome");

        userNameLabel.setText("<userName>");

        addAppButton.setText("Add New App");
        addAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAppButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(welcomeLabel)
                .addGap(6, 6, 6)
                .addComponent(userNameLabel))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(addAppButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel)
                    .addComponent(userNameLabel))
                .addGap(6, 6, 6)
                .addComponent(addAppButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAppButtonActionPerformed
    ThesisDatabase.window.selectPanel(0);
    }//GEN-LAST:event_addAppButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAppButton;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
