/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thesisdatabase;

import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author waltersquires
 */
public class QueriesPanel extends javax.swing.JPanel {

    /**
     * Creates new form queriesPanel
     */
    public QueriesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        addAppButton = new javax.swing.JButton();
        viewAppDataButton = new javax.swing.JButton();
        appId = new javax.swing.JTextField();
        appPrivilegeButton = new javax.swing.JButton();

        welcomeLabel.setText("Welcome");

        userNameLabel.setText("<userName>");

        addAppButton.setText("Add New App");
        addAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAppButtonActionPerformed(evt);
            }
        });

        viewAppDataButton.setText("View App Data");
        viewAppDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAppDataButtonActionPerformed(evt);
            }
        });

        appPrivilegeButton.setText("View App Privilege Statuses");
        appPrivilegeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appPrivilegeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(welcomeLabel)
                        .addGap(6, 6, 6)
                        .addComponent(userNameLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addAppButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewAppDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(appId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appPrivilegeButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel)
                    .addComponent(userNameLabel))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAppButton)
                    .addComponent(appPrivilegeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewAppDataButton)
                    .addComponent(appId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAppButtonActionPerformed
    ThesisDatabase.window.selectPanel(0);
    }//GEN-LAST:event_addAppButtonActionPerformed

    private void viewAppDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAppDataButtonActionPerformed
     try
     {
       ResultSet app = ThesisDatabase.viewApp(Integer.parseInt(appId.getText()));
        while (app.next()) {
              String appType = app.getString("os");
              if (appType.equals("Android"))
              {
                  AndroidResults temp = ThesisDatabase.window.getAndroidPanel();
                  temp.jTable2.setValueAt(app.getString("appName"), 0, 0);
                  temp.jTable2.setValueAt(app.getString("developer"), 0,1);
                  temp.jTable2.setValueAt(app.getString("addedby"), 0, 2);
                  temp.jTable2.setValueAt(app.getString("dateadded"), 0, 3); 

                  DefaultTableModel model = (DefaultTableModel) temp.jTable1.getModel();

                  ResultSet permissions = ThesisDatabase.getPermissions(Integer.parseInt(appId.getText()));
                  int h= temp.jTable1.getRowCount();
                  int row = 0;
                  while(permissions.next())
                  {
                     temp.jTable1.setValueAt(permissions.getString("permissionName"), row, 0);
                     temp.jTable1.setValueAt(permissions.getBoolean("requested"), row,1);
                     temp.jTable1.setValueAt(permissions.getBoolean("required"), row, 2);
                     row++;
                     
                        if(row>= h)
                        {
                          h++;
                          model.setRowCount(h);
                        }
                  }
                  
                  ThesisDatabase.window.selectPanel(3);

              }
              //String appName = rs.getString(1);
              //System.out.print(appName);
              //String developer = rs.getString("os");
              //int id2 = rs.getInt("addedby");
              //String password = rs.getString("dateadded");
              //System.out.println("appName" + "\t" + developer +
              //                   "\t" + id2);
          }
     }
     catch(NumberFormatException e)
     {
          JOptionPane.showMessageDialog(ThesisDatabase.popUp,
          "Not an integer. Please try again",
          "Whoops!",
          JOptionPane.ERROR_MESSAGE);
     }  catch (SQLException ex) {
            Logger.getLogger(QueriesPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewAppDataButtonActionPerformed

    public void setName(String name)
    {
        userNameLabel.setText(name);
    }
    
    private void appPrivilegeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appPrivilegeButtonActionPerformed
        ThesisDatabase.window.selectPanel(4);
    }//GEN-LAST:event_appPrivilegeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAppButton;
    private javax.swing.JTextField appId;
    private javax.swing.JButton appPrivilegeButton;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JButton viewAppDataButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
